basePath: /
host: localhost:9000
info:
  contact: {}
  description: This is the API documentation for the Kowtha backend.
  title: Kowtha API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
